version: '3.8'

services:
  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8080:8080"
    volumes:
      - ./backend:/app
      - /app/node_modules
      # Modificăm aici să bată cu structura ta de fișiere
      - ./database:/app/database 
    environment:
      - PORT=8080
      # ADAUGĂ /app ÎN FAȚĂ AICI:
      - SQLITE_DB_PATH=/app/database/assets/health_app.db 
    restart: always